### ISSUE TITLE
porting connect prism to gulp

### ISSUE THREAD

**Issue by joshikeerti** [seglo/grunt-connect-prism#2]

**Comment by samithaf** [comment]
hey @seglo thanks for the wonderful plugin. I am using Gulp version of the plugin and i can see grunt been added as a dependency in to my project now because grunt is been defined as peerDependencies in the project. Is there any reason for doing it?

**Comment by seglo** [comment]
@samithaf I assume you're referring to `connect-prism`?  That's a good question.  I use grunt to run the tests, I'm not sure why I kept it as a peer dependency.

**Comment by samithaf** [comment]
@seglo yup I am referring to connect-prism. If it only uses in tests then I believe that you can remove grunt :)

**Comment by seglo** [comment]
@samithaf I've pushed connect-prism 1.0.6 with it removed!

**Comment by samithaf** [comment]
@seglo thanks mate
