### ISSUE TITLE
Feature Request: Runtime configuration options

### ISSUE THREAD

**Issue by cthrax** [seglo/grunt-connect-prism#8]
First off, I love this tool!

As I've used it, a use case that I've come up with is to mock different scenarios of the same call. While this could be accomplished through multiple targets, starting up and shutting down grunt, segregating protractor specs and adding targets for each new case is unappealing.

It would be awesome to have the middleware pick up on certain context or headers or something that allows run-time configuration of the following options:
- mock location (so that multiple sets of mocks can be used)
- delay
- https

I'm sure this certainly isn't high priority, but I thought I would throw it out there.

Thanks again for the great project!

**Comment by seglo** [comment]
I finally released a first version of an API.  If you want to check it out in action I'd recommend reviewing the updated [`prism-sample-project`](https://github.com/seglo/prism-sample-project).  I added some tests that make use of it.  If you have any other API related issues you'd like to raise, please add them on the [`connect-prism`](https://github.com/seglo/connect-prism) issue tracker.

**Comment by cthrax** [comment]
This looks great man! I'm still integrating it into my protractor tests, but initial results are just what I was looking for. Thanks for taking the time!

**Comment by seglo** [comment]
You're welcome! Let me know if you have any questions or more suggestions.
